name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Main

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image for notifyagent-frontend
      uses: docker/build-push-action@v2
      with:
        context: ./client
        push: true
        platforms: linux/amd64,linux/arm/v7
        tags: parmati/notifyagent-fe:latest

    - name: Build and push Docker image for notifyagent-api
      uses: docker/build-push-action@v2
      with:
        context: ./api
        push: true
        platforms: linux/amd64,linux/arm/v7
        tags: parmati/notifyagent-api:latest