name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Main

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Determine Docker tag
      id: tag
      run: |
        if [ "${{ github.ref_name }}" == "main" ]; then
          echo "tag=latest" >> $GITHUB_ENV
        else
          sanitized_branch=$(echo "${{ github.ref_name }}" | sed 's#[^a-zA-Z0-9_.-]#-#g')
          echo "tag=${sanitized_branch}" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image for NotifyAgent
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm/v7
        tags: parmati/notifyagent:${{ env.tag }}